[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.28"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 1_000_000

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@uniswap-v3-core/=lib/uniswap-v3-core/contracts/",
    "@createx-forge=lib/createx-forge/",
]

[fuzz]
runs = 1024
